"use client";
/* eslint-disable @next/next/no-html-link-for-pages, @next/next/no-img-element */
import React, { useEffect, useState } from "react";
import { Choice, Field, Info, ReviewBlock, SummaryStrip } from "../../customer-account/sections/CustomerAccountSections";
import { ProductLine } from "../../quotation/sections/QuotationSections";
import { Field, ReviewBlock } from "../../../landing/shared/FormControls";
export function AdminPage({module="dashboard"}:{module?:string}){
  const [summary,setSummary]=useState({referrals:0,enquiries:0,recentAudit:[] as {id:number;action:string;entityType:string;details:string;createdAt:string}[]});
  const [query,setQuery]=useState("");
  const [notice,setNotice]=useState("");
  useEffect(()=>{fetch("/api/admin/summary").then(r=>r.ok?r.json():Promise.reject()).then(setSummary).catch(()=>undefined)},[]);
  const items=[["Dashboard","dashboard"],["Products","products"],["Referrals","referrals"],["Enquiries","enquiries"],["Customers","customers"],["Bookings","bookings"],["Content","content"],["Support","support"],["Policies","policies"],["Settings","settings"]];
  const title=items.find(x=>x[1]===module)?.[0]||"Dashboard";
  const tableRows=module==="referrals"?[["REF-1048","Mia Chen","Wedding","Qualified","$62.00"],["REF-1047","Noah Williams","Corporate","Pending","—"],["REF-1046","Ava Singh","Birthday","Paid","$48.00"]]:module==="products"?[["PRD-001","White Bistro Chair","Chairs","420 units","Active"],["PRD-014","Rustic Trestle Table","Tables","86 units","Active"],["PRD-028","Festoon Light Set","Lighting","54 sets","Active"]]:[["ENQ-133","Amelia Thompson","Wedding","14 Nov 2026","New"],["ENQ-132","Daniel Kim","Corporate","08 Sep 2026","Assigned"],["ENQ-131","Priya Shah","Birthday","22 Aug 2026","Quoted"]];
  const visibleRows=tableRows.filter(row=>row.join(" ").toLowerCase().includes(query.toLowerCase()));
  const exportRows=()=>{const csv=[["Reference","Name / record","Type","Details","Status"],...visibleRows].map(row=>row.map(cell=>`"${cell.replaceAll('"','""')}"`).join(",")).join("\n");const url=URL.createObjectURL(new Blob([csv],{type:"text/csv"}));const link=document.createElement("a");link.href=url;link.download=`sk-event-hire-${module}.csv`;link.click();URL.revokeObjectURL(url);setNotice(`${visibleRows.length} ${title.toLowerCase()} record${visibleRows.length===1?"":"s"} exported.`)};
  const createRecord=()=>{location.href=module==="referrals"?"/referrals":module==="products"?"/products":"/contact"};
  return <div className="admin-shell"><aside><a href="/admin" className="admin-brand admin-logo" aria-label="SK Event Hire admin home"><img src="/images/sk-event-hire-social-logo.png" alt="SK Event Hire"/><small>ADMIN</small></a><nav>{items.map(x=><a className={module===x[1]?"active":""} href={x[1]==="dashboard"?"/admin":`/admin-${x[1]}`} key={x[1]}><i>{["⌂","▦","↗","✉","♙","▤","✎","?","▣","⚙"][items.indexOf(x)]}</i>{x[0]}</a>)}</nav><a className="admin-exit" href="/">← View public website</a></aside><main><header><div><small>SK Event Hire administration</small><h1>{title}</h1></div><div><span>QA</span><b>QTechy Admin</b></div></header><section className="admin-kpis">{[["Products","42","Catalogue records"],["Open enquiries",String(Math.max(12,summary.enquiries)),"Needs response"],["Tracked referrals",String(Math.max(6,summary.referrals)),"Customer program"],["Upcoming bookings","18","Next 30 days"]].map(x=><article key={x[0]}><small>{x[0]}</small><b>{x[1]}</b><span>{x[2]}</span></article>)}</section><section className="admin-panel"><header><div><span>{title.toUpperCase()}</span><h2>{module==="dashboard"?"Operational overview":`${title} management`}</h2></div><div><label>⌕<input value={query} onChange={event=>setQuery(event.target.value)} placeholder={`Search ${title.toLowerCase()}`}/></label><button type="button" onClick={exportRows}>Export</button><button type="button" className="admin-primary" onClick={createRecord}>＋ Create new</button></div></header>{notice&&<p className="form-success" role="status">{notice}</p>}<div className="admin-table"><b>Reference</b><b>Name / record</b><b>Type</b><b>Details</b><b>Status</b><b>Actions</b>{visibleRows.flatMap(x=>[...x.map((y,i)=><span key={`${x[0]}${i}`}>{y}</span>),<span key={`${x[0]}a`}><button type="button" onClick={()=>setNotice(`${x[0]} selected for review.`)}>View</button><button type="button" onClick={()=>setNotice(`${x[0]} is ready for an authorised update.`)}>Edit</button></span>])}</div>{!visibleRows.length&&<p className="admin-empty">No records match “{query}”.</p>}</section><section className="admin-lower"><article><span>RECENT ACTIVITY</span><h2>Audit history</h2>{summary.recentAudit.length?summary.recentAudit.map(x=><p key={x.id}><b>{x.action} · {x.entityType}</b><small>{x.details} · {new Date(x.createdAt).toLocaleString("en-AU")}</small></p>):[["UPDATE · product","White Bistro Chair availability updated"],["CREATE · enquiry","Wedding enquiry received"],["APPROVE · referral","Referral REF-1048 qualified"]].map(x=><p key={x[1]}><b>{x[0]}</b><small>{x[1]}</small></p>)}</article><article><span>SYSTEM STATUS</span><h2>Backend connections</h2><p><b>Database</b><small>Connected · D1 persistent records</small></p><p><b>Referral API</b><small>GET and POST active</small></p><p><b>Enquiry API</b><small>Validated submissions active</small></p><p><b>Audit trail</b><small>Immutable create actions recorded</small></p></article></section></main></div>;
}

export const accountData: Record<string, {active:string; eyebrow:string; title:string; text:string; cards:[string,string,string][]}> = {
  overview:{active:"Overview",eyebrow:"Customer overview",title:"Good afternoon, Alex",text:"Your next event is on track. Here is what needs your attention now.",cards:[["Next event","Garden wedding","14 November · Confirmed"],["Balance due","$1,240.00","Due 30 October"],["Open quotation","1 ready to review","Expires 31 July"],["Unread messages","3 updates","Logistics & quotation"]]},
  quotes:{active:"Quotes",eyebrow:"Quotation centre",title:"Your quotations",text:"Review active proposals, request changes and follow accepted quotations into reservation.",cards:[["Q-260724-084","Garden wedding","Ready to review"],["Q-260615-031","Corporate lunch","Revision issued"],["Q-251120-092","40th birthday","Converted to booking"]]},
  "payments-documents":{active:"Payments & documents",eyebrow:"Payments & documents",title:"Balances, receipts and agreements",text:"Keep every deposit, balance, refund and booking document together.",cards:[["Balance due","$1,240.00","Garden wedding"],["Deposit received","$1,280.00","Visa ending 4821"],["Tax invoice","INV-260724-042","PDF ready"],["Rental agreement","Signed 18 July","Download copy"]]},
  "delivery-returns":{active:"Delivery & returns",eyebrow:"Event logistics",title:"Delivery, collection and returns",text:"See confirmed service windows, venue access notes and return obligations.",cards:[["Delivery","14 Nov · 10am–12pm","Richmond Town Hall"],["Setup","Complete by 2:00pm","Rear loading entrance"],["Collection","15 Nov · 9am–11am","SK collection"],["Return condition","Standard guidance","Report an issue"]]},
  messages:{active:"Messages",eyebrow:"Conversations",title:"Messages with SK Event Hire",text:"Keep quote, booking and support conversations connected to the right record.",cards:[["Garden wedding","Logistics team","2 unread"],["Quotation Q-260724-084","Event consultant","1 unread"],["Payment confirmation","Accounts team","Received"],["General support","Customer care","Reply within 1 day"]]},
  rewards:{active:"Rewards",eyebrow:"Reward cashback",title:"Your event rewards",text:"Track pending, available, used and expired cashback from eligible completed rentals.",cards:[["Available","$84.00","Ready to apply"],["Pending","$38.40","Garden wedding"],["Used","$120.00","Lifetime"],["Lifetime earned","$242.40","Since 2024"]]},
  affiliate:{active:"Affiliate",eyebrow:"Refer & earn",title:"Share events. Earn commission.",text:"Invite new customers and follow each privacy-safe referral from signup to eligible payout.",cards:[["Referral code","ALEXEVENTS","Copy code"],["Link clicks","48","Last 30 days"],["Qualified referrals","6","2 pending"],["Available earnings","$186.00","Payout ready"]]},
  "saved-products":{active:"Saved products",eyebrow:"Your shortlist",title:"Saved products",text:"Keep favourite products ready for a future quote or repeat event.",cards:[["Bentwood Chair","Natural white","From $12"],["Festoon Light Set","Warm white · 20m","From $90"],["Rustic Timber Table","1.8 metres","From $120"],["Timber Welcome Sign","Personalised A1","From $145"]]},
  "reviews-account":{active:"Your reviews",eyebrow:"Verified reviews",title:"Your event reviews",text:"Review completed bookings and track submitted feedback.",cards:[["40th birthday","Eligible to review","Review by 10 Aug"],["Corporate launch","★★★★★","Published"],["Garden wedding","Upcoming","Available after return"],["Review photos","2 approved","Manage consent"]]},
  profile:{active:"Profile",eyebrow:"Personal information",title:"Your customer profile",text:"Maintain verified contact details, saved addresses and event preferences.",cards:[["Alex Morgan","Verified customer","Edit details"],["Email","alex.morgan@example.com","Verified"],["Mobile","0412 345 678","Verified"],["Saved addresses","3 addresses","Manage"]]},
  "settings-security":{active:"Settings & security",eyebrow:"Account controls",title:"Security, notifications and privacy",text:"Manage sign-in methods, active sessions, communication and sensitive requests.",cards:[["OTP methods","Email & SMS","Both verified"],["Active sessions","2 devices","Review sessions"],["Notifications","Operational on","Marketing optional"],["Privacy","Export or delete","Re-verification required"]]},
};

export function AccountOverview({ kind }: { kind:string }) {
  const d = accountData[kind] || accountData.overview;
  return <main><div className="crumb">{d.active} <span>›</span> Overview</div><section className="page-hero"><div><div className="eyebrow">{d.eyebrow}</div><h1>{d.title}</h1><p>{d.text}</p></div><a className="primary account-action" href={kind === "quotes" ? "/create-quote-01" : "/contact"}>{kind === "quotes" ? "Create new quotation" : "Get help"} →</a></section><div className="account-card-grid">{d.cards.map((x,i)=><article className="card account-card" key={x[0]}><i>{["◇","▦","▤","✦"][i]}</i><span><small>{x[0]}</small><b>{x[1]}</b><em>{x[2]}</em></span><a href={kind==="quotes" && i===0?"/quotation-details":"#"}>Open →</a></article>)}</div><section className="card account-panel"><div className="section-head"><div><div className="eyebrow">Recent activity</div><h2>What changed</h2></div><a href="#">View all activity →</a></div>{[["Today · 9:10am","Warehouse preparation scheduled","Booking SK-261114-042"],["Yesterday · 4:32pm","Quotation ready to review","Q-260724-084"],["18 July · 2:43pm","Deposit received","$1,280.00 · Visa ending 4821"],["16 July · 11:08am","Reward cashback pending","$38.40 after completion"]].map(x=><div className="activity-row" key={x[0]}><small>{x[0]}</small><b>{x[1]}</b><span>{x[2]}</span><a href="#">View</a></div>)}</section></main>;
}

export const quotationStages = [
  ["quotation-details","Quotation details","Garden wedding quotation","Review items, dates, services, charges, GST and terms before continuing."],
  ["quotation-review","Review & accept","Review quotation acceptance","Confirm the current quotation and acknowledge the rental terms."],
  ["quotation-reservation","Request reservation","Reserve the quoted items","Ask us to hold the quoted stock while availability is checked again."],
  ["quotation-availability","Availability check","Everything is available","The quoted items, crew and delivery window passed the final recheck."],
  ["quotation-payment","Deposit request","Pay the required deposit","A $1,280.00 deposit is required to confirm this reservation."],
  ["quotation-processing","Secure processing","Confirming your booking","We are authorising the deposit and creating your rental order."],
  ["quotation-result","Booking confirmed","Your reservation is confirmed","Your quotation is now booking SK-261114-042 and the equipment is allocated."],
] as const;

export function QuotationFlow({ path }:{path:string}) {
  const idx = Math.max(0, quotationStages.findIndex(x=>x[0]===path));
  const s = quotationStages[idx];
  const next = quotationStages[Math.min(idx+1,quotationStages.length-1)][0];
  return <main className="flow"><div className="crumb">Quotes <span>›</span> {s[1]}</div><section className="page-hero"><div><div className="eyebrow">{s[1]}</div><h1>{s[2]}</h1><p>{s[3]}</p></div><div className="step-pill">{idx+1} of {quotationStages.length}</div></section><SummaryStrip/><section className={`card flow-card ${path==="quotation-result"?"result-card":""}`}>{path==="quotation-result"?<div className="quote-result"><div className="result-icon">✓</div><div className="eyebrow">Booking SK-261114-042</div><h2>Deposit received and stock allocated</h2><p>Your confirmation, tax invoice and rental agreement are ready in your account.</p><div className="result-facts"><Info label="Deposit" value="$1,280.00 paid"/><Info label="Delivery" value="14 Nov · 10am–12pm"/><Info label="Status" value="Confirmed"/></div></div>:<><div className="review-grid"><ReviewBlock title="Event & rental" rows={[["Event","Garden wedding"],["Date","14–15 November 2026"],["Venue","Richmond Town Hall"],["Guests","80"]]}/><ReviewBlock title="Quotation summary" rows={[["Quote","Q-260724-084"],["Items","93 hire items"],["Services","Delivery, setup & collection"],["Valid until","31 July 2026"]]}/></div><div className="quote-products compact-products"><ProductLine name="Bentwood Chairs" detail="Natural white" qty="80" price="$960.00"/><ProductLine name="Rustic Timber Tables" detail="1.8 metre" qty="9" price="$1,080.00"/><ProductLine name="Festoon Light Sets" detail="Warm white" qty="4" price="$360.00"/></div><div className="charge-table"><div><span>Hire & services</span><b>$3,490.91</b></div><div><span>GST</span><b>$349.09</b></div><div className="grand"><span>Total</span><b>$3,840.00</b></div></div>{idx>0&&<Choice checked icon="✓" title={idx===4?"Use Visa ending 4821":"I confirm these details"} text="I understand availability and payment must be confirmed before this becomes a booking."/>}</>}</section><div className="footer-actions"><a className="secondary" href={idx===0?"/quotes":`/${quotationStages[idx-1][0]}`}>Back</a><a className="primary" href={`/${next}`}>{idx===quotationStages.length-2?"View confirmed booking":idx===4?"Pay $1,280 deposit":"Continue"} →</a></div></main>;
}

export function AuthPage({ type }:{type:string}) {
  const map:Record<string,[string,string,string]>={ "sign-in":["Welcome back","Sign in to your SK Event Hire account","Enter your verified email or Australian mobile number to receive a secure code."], otp:["Check your messages","Enter your 6-digit verification code","We sent a code to a•••@example.com. It expires in five minutes."], "create-account":["Create your customer account","Keep every event in one place","Add your contact details, accept the account terms and verify your preferred sign-in method."], "complete-profile":["Complete your profile","Make future event requests faster","Confirm your name, preferred address and communication settings. Optional details can be added later."]};
  const d=map[type]||map["sign-in"];
  return <div className="auth-shell"><aside><a className="auth-brand-logo" href="/" aria-label="SK Event Hire home"><img src="/images/sk-event-hire-website-logo.png" alt="SK Event Hire"/></a><div><div className="eyebrow">Plan with confidence</div><h1>Quotes, bookings and event logistics in one calm place.</h1><p>Securely review proposals, make payments, follow deliveries and keep every document connected.</p></div><small>Melbourne event hire & planning</small></aside><main><a className="back-home" href="/">← Back to website</a><section className="auth-card"><div className="eyebrow">{type==="otp"?"Secure verification":"Customer account"}</div><h2>{d[0]}</h2><h3>{d[1]}</h3><p>{d[2]}</p><div className="form-grid auth-form">{type==="otp"?<Field wide label="Verification code" value="2  8  4  1  7  5"/>:<><Field wide label={type==="sign-in"?"Email or mobile":"Full name"} value={type==="sign-in"?"alex.morgan@example.com":"Alex Morgan"}/>{type!=="sign-in"&&<><Field wide label="Email address" value="alex.morgan@example.com"/><Field wide label="Mobile number" value="0412 345 678"/></>}</>}</div><a className="primary auth-button" href={type==="sign-in"?"/otp":type==="otp"?"/overview":type==="create-account"?"/complete-profile":"/overview"}>{type==="sign-in"?"Send secure code":type==="otp"?"Verify and continue":"Save and continue"} →</a>{type==="sign-in"&&<p className="auth-switch">New to SK Event Hire? <a href="/create-account">Create an account</a></p>}</section></main></div>;
}
